name: Pytest and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.5.1"

    - name: Install dependencies and run tests with coverage
      run: |
        poetry install --only=test
        poetry run coverage run -m pytest
        poetry run coverage report -m
